gg:
  css: [./css/gg.css]
  jshead: [./js/d3.v3.js,./js/gg.js,./js/lodash.js]
  cdn:
    css:
      - "./css/gg.css"
    jshead: 
      - "./js/d3.v3.js"
      - "./js/gg.js"
      - "./js/lodash.js"

