gg:
  css: [css/gg.css]
  jshead: [js/d3.v3.js,js/gg.js]
  cdn:
    css:
      - "http://timelyportfolio.github.io/rCharts_gg/css/gg.css"
    jshead: 
      - "http://d3js.org/d3.v3.min.js"
      - "http://timelyportfolio.github.io/rCharts_gg/js/gg.js"
